### ISSUE TITLE
Add operators to Lookup

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cache#10]
- `includeKeys` - A predicate on keys that should ALWAYS be cached
 - `excludeKeys` - A predicate on keys that should NEVER be cached
 - Combining lookup functions?
   - `orElse` (fallback)
   - `race` (first success)
  - Unary operators
    - `onSuccess(v => ZIO(...))`
    - `onFailure(e => ZIO(...))`

```scala
val lookup2 = lookup.includeKeys(List("SPECIAL_KEY1", "SPECIAL_KEY2") contains _).excludeKeys(_ == "SPECIAL_KEY3")
```

**Comment by hollinwilkins** [comment]
Another useful operator would be something that builds a chain of cache lookups, so you can first check an in-memory cache, then check a remote cache such as redis, and finally fallback to calculating the value.

A cache the is upstream could populate with the downstream values. This is very similar to the orElse operator, but fills upstream caches w/ downstream values.
