### ISSUE TITLE
Ability to transform value

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio-cache#137]
Much like there is a constructor to transform the key, it would be great to have one to transform the value. The use case I have right now is an http call where the ttl is controlled by the `Cache-Control` header in the response, but the value stored in the cache is the decoded body. Does that make sense?

```
def makeUltimate[In, Key, Environment, Error, Result, Value](
    capacity: Int,
    lookup: Lookup[In, Environment, Error, Result]
  )(
    timeToLive: Exit[Error, Value] => Duration,
    keyBy: In => Key,
    valueFrom: Result => ZIO[Environment, Error, Value]
  )(implicit trace: Trace): URIO[Environment, Cache[In, Error, Value]]
```

Home stretch: add a conditional lookup function, so that in my use case instead of doing a blanket `GET` request again it would add the `If-Modified-Since` header.

**Comment by adamgfraser** [comment]
@regiskuckaertz I think the case of `keyBy` is different in that it is functionality that can't be implemented in user land. If I am understanding you correctly you can currently just do `cache.get(key).flatMap(valueFrom)`.

You can also do:

```scala
def  mappedCache[Key, Err, Value, Result](
  cache: Cache: Key, Err, Value, Result]
)(f: Result => ZIO[Environment, Error, Value]): Cache[Key, Err, Value] =
  new Cache[Key, Err, Value] {
    def get(key: Key): ZIO[Any, Err, Value] =
      cache.flatMap(f)
  }
```

This could potentially be wrapped up in a `map` operator on `Cache` though we have moved away from that with the simplification of polymorphic concurrent data structures in ZIO 2.
