### ISSUE TITLE
Option to turn off caching errors

### ISSUE THREAD

**Issue by ithinkicancode** [zio/zio-cache#41]
### Motivation
Currently we cache errors when lookup function calls fail. While this can be beneficial (e.g. as a countermeasure to malicious attacks that send bogus requests for non-existing entities), there are times when such behavior is not desired. We should give users the option to opt out.

**Comment by ghostdogpr** [comment]
This is currently possible by using `Cache.makeWith`. The parameter `timeToLive: Exit[Error, Value] => Duration` lets you set a different TTL for errors, which could be zero.
