### ISSUE TITLE
Call CachingPolicy#evict more often

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cache#6]
A goal should be that if all entries should expire after 1 hour, then if the cache is left alone for a sufficient amount of time, eventually, it contains no entries.

**Comment by jdegoes** [comment]
Alternative idea: remove `Evict`, move `expirationTime` to `EntryStats` (rename), implicitly prioritize first by expiration time, and only for equal expiration times use the first (user-defined) priority. Probably this means `CachingPolicy` can be nothing more than `Priority`, i.e., we can rename `Priority` => `CachingPolicy`.

**Comment by hollinwilkins** [comment]
Implicitly ordering by expirationTime will mean that it is very unlikely for any user-defined priorities to ever be used to determine eviction. To support both TTLs and user-defined eviction policies (based on size of entries, for instance), I think it would be necessary to store two data structures, one sorting elements by TTL and another sorting by user-defined priority.
