### ISSUE TITLE
Test fails when executed in IntelliJ

### ISSUE THREAD

**Issue by ravinagabhyru** [zio/zio-cache#63]
When tests are executed using IntelliJ, tests fail with the following output (varies with each run).

- CacheSpec
  - cacheStats
    Test failed after 4 iterations with input: 13
    Original input before shrinking was: 296005039
    • 47 was not equal to 49
    hits == 49L
    hits = 47
    at /home/ravi/projects/zio-cache/zio-cache/shared/src/test/scala/zio/cache/CacheSpec.scala:22
    
    Test failed after 4 iterations with input: 13
    Original input before shrinking was: 296005039
    • 53 was not equal to 51
    misses == 51L
    misses = 53
    at /home/ravi/projects/zio-cache/zio-cache/shared/src/test/scala/zio/cache/CacheSpec.scala:23
    
  + invalidate
  + invalidateAll
  + lookup
    + sequential
    + concurrent
    + capacity
  + `refresh` method
    + should update the cache with a new value
    + should update the cache with a new value even if the last `get` or `refresh` failed
    + should get the value if the key doesn't exist in the cache
  + size
Ran 10 tests in 4 s 263 ms: 9 succeeded, 0 ignored, 1 failed
- CacheSpec
  - cacheStats
    Test failed after 4 iterations with input: 13
    Original input before shrinking was: 296005039
    • 47 was not equal to 49
    hits == 49L
    hits = 47
    at /home/ravi/projects/zio-cache/zio-cache/shared/src/test/scala/zio/cache/CacheSpec.scala:22
    
    Test failed after 4 iterations with input: 13
    Original input before shrinking was: 296005039
    • 53 was not equal to 51
    misses == 51L
    misses = 53
    at /home/ravi/projects/zio-cache/zio-cache/shared/src/test/scala/zio/cache/CacheSpec.scala:23
    

Process finished with exit code 1

**Comment by ithinkicancode** [comment]
I have the same problem with IntelliJ. Most likely a problem with IntelliJ, as running the tests via sbt always passes.

**Comment by ravinagabhyru** [comment]
After some debugging, I realized, IntelliJ created a configuration using zioCacheNative as the classpath. After changing the classpath to zioCacheJVM, tests run without any errors. zioCacheNative uses HashMap as the Map implementation, while zioCacheJVM uses ConcurrentHasMap as the Map implementation.

**Comment by ithinkicancode** [comment]
Yes, I heard about IntelliJ's classpath problem. One suggestion I read is to launch IDEA from command line as opposed to launching from the app icon, on MacOS.
