### ISSUE TITLE
Add memory estimation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cache#7]
Maybe we create an `Estimator[Value]` that can estimate the size of a value, which can be passed into `Cache.make`.

**Comment by hollinwilkins** [comment]
This is the memory estimator that Spark uses for Java objects: https://spark.apache.org/docs/latest/api/java/index.html?org/apache/spark/util/SizeEstimator.html

https://github.com/apache/spark/blob/3a299aa6480ac22501512cd0310d31a441d7dfdc/core/src/main/scala/org/apache/spark/util/SizeEstimator.scala

**Comment by adamgfraser** [comment]
@hollinwilkins Thank you! 🙏

**Comment by ben-manes** [comment]
FYI, https://openjdk.java.net/jeps/8249196
