### ISSUE TITLE
Enhance cache lookup

### ISSUE THREAD

**Issue by landlockedsurfer** [zio/zio-cache#96]
Hi!

While working with zio-cache I ran into a problem where `Key` alone does not provide enough information
to compute the cached `Value`.

As a motivating example let's assume that some request contains the user ID and some other data extracted
from a session cookie.
```scala
case class CookieData(data:String)
case class Request(userId:Int, cookieData:CookieData)

trait UserSessionDataComputationService {
  type UserSessionData
  def expensiveUserSessionDataComputation(request:Request):UIO[UserSessionData]
}
```
A cache lookup can trigger a `expensiveUserSessionDataComputation` call to compute the cached value.

With the current version of `zio-cache`, we can set `Key` to `Int`,
`Value` to `UserSessionData` and
`Environment` to `UserSessionDataComputationService`.
To run the effect and construct the cache we must provide a `UserSessionDataComputationService` once.
However, we cannot access the `Request` instance.
We cannot solve the problem by making `Request` part of the environment,
because the request would only be set once during cache creation instead of cache lookup.

One solution is to update the interface of Cache's `get`,`lookupValue` and `refresh` methods to return
a `ZIO[Environment,Error,Value]` instead of `IO[Error,Value]`.
In the example given above `Environment` is set to `Request` only.
`UserSessionDataComputationService` can be provided as input for a cache layer.

This branch shows a possible implementation with a demo app:
https://github.com/landlockedsurfer/zio-cache/commits/lookup-environment

Another solution is to project out the key from a given input. A new type variable `Input` is introduced
and a `keyByInput` function passed on cache creation to extract the key from the given input.

This branch shows a possible implementation for this solution including a demo app:
https://github.com/landlockedsurfer/zio-cache/commits/key-by-input

What do you think?

Kind regards,
Manfred

**Comment by jdegoes** [comment]
Would adding `Cache#contramap` / `Cache#contramapZIO` let us create a cache one key, then change it to another type??

**Comment by jdegoes** [comment]
This might imply adding another type param to `Cache`.

**Comment by landlockedsurfer** [comment]
Hi John!
That sounds like a very elegant solution! I will start working on that!

**Comment by regiskuckaertz** [comment]
Isn't that `makeWithKey`?
https://github.com/zio/zio-cache/blob/92105161445ccea71a7ffc36e15a964fdb01ab1a/zio-cache/shared/src/main/scala/zio/cache/Cache.scala#L133-L139

**Comment by landlockedsurfer** [comment]
Thanks for the update! Yes, that's working nicely now.
I noticed that it might make sense to support a `keyBy` setting for `ScopedCache` also.
